[package]
name = "spooderman"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cargo-watch = "8.4.1"
chrono = "0.4.31"
reqwest = {version = "0.11.18", features = ["blocking"]}
scraper = "0.16"
