name: Rust CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Rust
        uses: actions/setup-rust@v1
        with:
          rust-version: stable

      - name: Check out code
        uses: actions/checkout@v2

      - name: Build and test
        run: |
          cargo build --verbose
          # cargo test --verbose
  format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Rust
        uses: actions/setup-rust@v1

      - name: Format code
        run: cargo fmt -- --check
